### PR TITLE
Add information about SongDir configuration for flatpak

### PR DESCRIPTION
**Pull request by Bronkoknorb**

### CODE REVIEW

**Comment by s09bQ5** [comment]
Is that readme the place people look at for information on how to use the flatpak?
I've already added a similar sentence to [the description on Flathub](https://flathub.org/apps/eu.usdx.UltraStarDeluxe).

**Comment by Bronkoknorb** [comment]
Yes, that is also a good place. I found that sentence there. But the information how to change the default SongDir (in particular that the flatpak override command is needed first), was missing.
I think it would be good to add that both to the README and also to the description on flathub.

**Comment by barbeque-squared** [comment]
The readme section that's edited in this PR is the last remaining one that's still mostly as it was before I started moving things for end users towards the wiki. But that was more to make things workable for developers than a solution in itself (because it's impossible to PR against the wiki), so while it's still here I'm okay with this being changed.

(offtopic: see #660 for the discussion on what to do with the wiki long-term)

**Comment by Bronkoknorb** [comment]
Will you merge my PR?

**Review by basisbit — APPROVED** [review]
looks good to me. Thank you for helping to improve our documentation!

**Pull request merged**
