### PR TITLE
Support soundcards offering over two channels

### PR DESCRIPTION
**Pull request by HermannDppes**
Work towards fixing #339 has started on this branch. For those who use such soundcards, this branch might already be preferable to master. For everyone else, it definitely isn't.

### CODE REVIEW

**Comment by basisbit** [comment]
Thank you a lot for this pull request! There are still some things to do: the UI code, theme and maybe also the settings code still need adjustments to fully make 3 or 4 channel audio input devices selectable and usable in the game. Those changes will be done within this pull request fork, eventually get reviewed and then one of the other USDX devs will merge this pull request.
@HermannDppes could you maybe post here some screenshots of the audio record settings screen ingame with such a microphone connected and channel 3 or 4 connected?

**Comment by HermannDppes** [comment]
I'm working on the UI right now but your code is not exactly well-document, as far as I am able to tell, so the pace is expectedly rather slow. Convincing GitHub to accept my screenshots was non-trivial but now it works. Everyone therefore has the option to gaze at my „progress“ in all its non-glory:

A two channel mic leaving lots of unused space
A four channel mic, fully usable

**Comment by ZePhyr1987** [comment]
is there a possibility to add even more, with maybe scrolling ui or just in the config file? 
im used to use at least 6 mics

**Comment by HermannDppes** [comment]
Config file would already work. Simply edit [src/media/UAudioInput_Portaudio.pas](https://github.com/UltraStar-Deluxe/USDX/blob/master/src/media/UAudioInput_Portaudio.pas) to your desire, the offending lines are

```pascal
// portaudio returns a channel-count of 128 for some devices                 
// (e.g. the "default"-device), so we have to detect those                   
// fantasy channel counts.                                                   
if (channelCnt > 8) then                                                     
  channelCnt := 2; 
```

The GUI will be visually broken but functional, the config file should not make any problems. (Except for being rather overcrowded, e.g. if you happened to have two devices for 128 recognized channels each …) I recommend backing up the config file before starting the modified binary and trying to find values of `8` and `2` that cover your usecase without to much annoyance from the buggy devices.

The entire point of this PR and my ongoing fight against the code is making this accessible via the GUI and I plan on supporting as many channels as there might be, simply to get an appropriate payout for my troubles.

**Comment by HermannDppes** [comment]
That seems like a good point to pause work on this and maybe get some sleep. ^^

**Comment by s09bQ5** [comment]
@HermannDppes, you don't need to push every little change immediately. It is ok if you do one push once you believe the changes are ready to be merged.

**Comment by HermannDppes** [comment]
@s09bQ5 It's a force of habit for me. I adhere to the old adage of „Commit early, commit often.“ and do the same thing for pushing. Is there any problem with pushing everything immediately?

**Comment by s09bQ5** [comment]
Maintainers get an eMail for every push you do and every push triggers a three Travis and one AppVeyor build.

**Comment by HermannDppes** [comment]
Progress pic:
A screenshot showing that the two channel-to-player-assignment sliders have been replaced with one channel-selection slider and a single channel-to-player-assignment slider

It's nearly ready to be reviewed, right now I can only think of a single thing I yet have to do. The most dangerous changes are probably what I did with the internationalization (two new fields) and the themes (one field gone, two new ones). Other than that I hopefully should not have screwed up anything besides coding style and naming conventions. (And with some luck, not even that.)

@s09bQ5 Yeah, I see how that might be quite annoying. I have switched development to a different branch and will only update this branch when it seems appropriate.

**Comment by basisbit** [comment]
the UI change actually makes setup slower for people using the default SingStar/Wii microphones because now you have to switch input device and channel to figure out where the microphone you are using is, so you can set the desired numbers. I am wondering, what hardware are you using, so 2 input channels per input device is not enough? Would like to figure out if that actually is a common usecase

**Comment by HermannDppes** [comment]
We have an [audio interface](https://focusrite.com/usb-audio-interface/scarlett/scarlett-18i8) reporting  eighteen channels (only four of which are currently relevant for us) with four [SM 58 microphones](https://www.shure.com/en-US/products/microphones/sm58).

Given that #339 was there before me and [ZePhyr1987 immediately asked](https://github.com/UltraStar-Deluxe/USDX/pull/466#issuecomment-502404431) if I could support six mics, I would argue it is common enough to warrant some attention.

> the UI change actually makes setup slower for people using the default SingStar/Wii microphones because now you have to switch input device and channel to figure out where the microphone you are using is, so you can set the desired numbers.

Yes, in this case setup is made worse than before (except for the people who are confused by the old UI, we certainly would have been able to do our two mic setup faster in the current layout since we took quite a while to figure out what the numbers meant). I could special-case the two-channel devices to the old layout, but actually I would prefer for it to stay the new way while we think about a better way to do the configuration. That we assign channels to players instead of the other way 'round seems like a source of quite a few problems to me, on the usability side of things.

**Comment by basisbit** [comment]
ok :+1:

**Comment by HermannDppes** [comment]
This ensures that it stays possible to edit the config.ini manually. While my devices are detected for mere 32 channels, having 128 channels per device in there might make it really hard to quickly change something. Now, all the unused channels are omitted, making the config file even more accessible, ensuring that we can leverage more synergies in the blockchain-cloud than ever before! */end marketing*

**Comment by basisbit** [comment]
@HermannDppes for me this looks like ready to merge. Do you agree? Anything you still want to change?

**Pull request merged**
