### PR TITLE
allow compilation with more FFmpeg versions

### PR DESCRIPTION
**Pull request by s09bQ5**
This fixes issue #277.

### CODE REVIEW

**Comment by cRaZy-bisCuiT** [comment]
Should usdx now build on Debian 8 (3.2.5-1 with strech backports) and 9 (3.2.5-1)? by the way, many, many thanks for fixing the headers and checks! I had so much trouble to build ffmpeg and I do hope that it should build now. :)

**Comment by basisbit** [comment]
so far there is no support for ffmpeg 3.3.x as far as I know, so that will not yet work.

**Comment by s09bQ5** [comment]
@basisbit, you should take a closer look at what you merge.
This pull request adds support for 3.3.x by using the 3.2 headers.

**Comment by cRaZy-bisCuiT** [comment]
I can not compile on Raspberry Pi with Raspian Stretch:
`Compiling lib/ffmpeg-3.2/rational.pas
Assembling rational
/home/pi/USDX/src/lib/ffmpeg-3.2/libavutil/pixfmt.pas(83,49) Note: Values in enumeration types have to be ascending
Assembling avutil
/home/pi/USDX/src/lib/ffmpeg-3.2/avcodec.pas(383,52) Note: Values in enumeration types have to be ascending
Assembling avcodec
Compiling lib/ffmpeg-3.2/avformat.pas
Compiling lib/ffmpeg-3.2/avio.pas
Assembling avio
Assembling avformat
Compiling media/UMediaCore_FFmpeg.pas
/home/pi/USDX/src/media/UMediaCore_FFmpeg.pas(44,3) Fatal: Can't find unit swscale used by UMediaCore_FFmpeg
Fatal: Compilation aborted
Error: /usr/bin/ppcarm returned an error exitcode
Makefile:223: recipe for target '../game/ultrastardx' failed
make[1]: *** [../game/ultrastardx] Error 1
make[1]: Leaving directory '/home/pi/USDX/src'
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by s09bQ5** [comment]
This problem is not related to supporting specific FFmpeg revisions.
UMediaCore_FFmpeg.pas is just lacking a few {$IFDEF UseSWScale}s.
Try apt-get install libswscale-dev

**Comment by cRaZy-bisCuiT** [comment]
Thanks for your help! Actually I accidentally used a broken fpc version once again. fpc 3.0.0 isn't compiling on arm while 3.0.2 does fine!

**Comment by bohning** [comment]
@s09bQ5 After your comment I updated to ffmpeg 3.3.3 yesterday and ./configure tells me:

```
checking for libavcodec... yes (-L/usr/local/Cellar/ffmpeg/3.3.3/lib)
checking version of libavcodec... [57.89.100]
checking for avcodec_decode_audio in -lavcodec... no
checking for avcodec_decode_audio2 in -lavcodec... no
checking for img_convert in -lavcodec... no
checking for libavformat... yes (-L/usr/local/Cellar/ffmpeg/3.3.3/lib)
checking version of libavformat... [57.71.100]
checking for libavutil... yes (-L/usr/local/Cellar/ffmpeg/3.3.3/lib)
checking version of libavutil... [55.58.100]
checking version of ffmpeg... configure: error: 

Unsupported ffmpeg version, most recent version supported is 3.2.
```

If ffmpeg 3.3.3 is supported, this should be fixed. Can this be ignored for now? It does compile!

**Comment by s09bQ5** [comment]
You are either not using the current code or have forgotten to rerun ./autogen.sh.
The current code prints that the most recent supported version is 3.3.

**Comment by bohning** [comment]
Ah, my bad. Only ran configure without running autogen.sh first. Thanks for the clarification!

**Comment by cRaZy-bisCuiT** [comment]
Is there any script included in the code to generate Debian packages? I'd like to set up a separate building environment to build USDX, create packages and deploy it on another system.

The reason is that 1. compiling on the Pi is slow 2. using fpc backports from sid breaks Raspian / Debian 8.

**Pull request merged**
