### PR TITLE
Update AppImage dependencies

### PR DESCRIPTION
**Pull request by s09bQ5**
Depends on FFmpeg 6 PR. Will rebase after that one has been merged.
Updates everything we can update.
Enables a few more backends in SDL.

### CODE REVIEW

**Comment by s09bQ5** [comment]
Rebased and updated to the newest versions of SDL2, Lua, and sqlite.

**Comment by s09bQ5** [comment]
The 32 bit build failed due to temporary network problems. The build succeeded here: https://ci.appveyor.com/project/s09bQ5/usdx/builds/46928318

**Review by barbeque-squared — APPROVED** [review]

**Comment by s09bQ5** [comment]
I don't think anyone will test the appimages in-between releases. So there is no benefit in having it merged 3 weeks before the next release. With all changes residing in dists/linux/ there is zero change of breaking the Windows or macOS builds.

**Comment by barbeque-squared** [comment]
Oh, no this isn't about having it in three weeks _before_ the next release; even for game stuff, a few days is more than enough. But this is platform stuff, so it either works or it doesn't. The timing is just unlucky as I was about to start 2023.5.
(and you're right, at least I have never tested any appimage)

Into 2023.5 it goes then!

**Pull request merged**
