### PR TITLE
Use Git LFS for PE and font files

### PR DESCRIPTION
**Pull request by s09bQ5**
This moves all .exe, .dll, .debug, .ttc, and .ttf files to Git LFS storage.
I decided to do this for the fonts as well because the two biggest of them are almost 20 MB each.

We do have some audio files, videos, and pictures in the repository, but many of them are small.

### CODE REVIEW

**Review by bohning — APPROVED** [review]

**Comment by barbeque-squared** [comment]
> I decided to do this for the fonts as well because the two biggest of them are almost 20 MB each.

Good call!

**Comment by s09bQ5** [comment]
Shit, there is a 1 GB traffic limit for free accounts and we already hit that limit.
Force push to undo this pull request?

**Comment by barbeque-squared** [comment]
@s09bQ5 :+1: go ahead with a force push to undo this PR.
(I think you have the write access to do that? If not comment here and I'll do it manually)

**Comment by s09bQ5** [comment]
I can't force-push to master. The master branch is protected. @basisbit can you force-push 72e84737c59add63e749aa04cc784feba89494b5 to master or change the protection of the master branch?

**Comment by bohning** [comment]
Please try again now, @s09bQ5.

**Comment by s09bQ5** [comment]
Still protected:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request. Cannot force-push to this branch
To github.com:UltraStar-Deluxe/USDX.git
 ! [remote rejected]   pre-lfs -> master (protected branch hook declined)
```

**Comment by bohning** [comment]
Now?

**Comment by s09bQ5** [comment]
same

**Comment by bohning** [comment]
Hmm...
image
Then I don't know how to disable it without deleting the entire master branch rule.

**Comment by barbeque-squared** [comment]
it probably has something to do with this: https://github.com/settings/organizations

for me it looks like this:
2024-07-30-130838_385x130_scrot

I'm assuming it's the same for s09bQ5

@bohning that screenshot looks like it's doing something on the organization level, which is weird because https://github.com/orgs/UltraStar-Deluxe/people lists only 4 people. I don't know who the other 4 even would be. It has a search box though to add more people, just add s09bQ5 manually in there? (and then remove again once force-pushed)

(I'll be on Discord in about 2-3 hours from now, in case we've had no luck by then)

**Comment by s09bQ5** [comment]
I can't join an organization because I still haven't set up 2FA.
I guess the easiest would be if one of you does the force push.

**Comment by bohning** [comment]
I tried adding @s09bQ5, but the only choice I could make was UltraStar-Deluxe/contributors. Now I added @s09bQ5 manually, try again now.

image

**Comment by s09bQ5** [comment]
success

**Pull request merged**
