### PR TITLE
Correcting formats of dates for each language (CLDRv42)

### PR DESCRIPTION
**Pull request by PonPonTheBonBon**
For each language, the dateformat is updated and corrected for each language, taken from CLDR v42 (2022-10-17)

Most languages had the format MM.DD.YYYY which isn't appropriate for most language. Each language has been changed to reflect the exact format provided by CLDR, the standard used by Microsoft, Android, Apple to provide dates on the system. Czech, French, Luxembourgish and Portuguese were already using DMY, but has been modified to match CDLR instead, for consistency.

The file language.new has also been updated and changed from MM.DD.YYYY to DD.MM.YYYY to reflect the most common format globally. English, since it's used globally with different formats, has been changed from MM.DD.YYYY to YYYY-MM-DD, a neutral ISO 8601-format, unless specific versions of English can be added, such as UK and US English.

Changes:
* Catalan: MM.DD.YYYY → D/M/YYYY
* Chinese: MM.DD.YYYY → YYYY/M/D
* Croatian: MM.DD.YYYY → DD. MM. YYYY.
* Czech: DD. MM. YYYY → DD.MM.YYYY
* Danish: MM.DD.YYYY → DD.MM.YYYY
* Dutch: MM.DD.YYYY → DD-MM-YYYY
* English: MM.DD.YYYY → YYYY-MM-DD
* Euskara: MM.DD.YYYY → YYYY/M/D
* Finnish: MM.DD.YYYY → D.M.YYYY
* French: DD.MM.YYYY → DD/MM/YYYY
* Gaelic: MM.DD.YYYY → DD/MM/YYYY
* Galician: unchanged
* German: unchanged
* Greek: MM.DD.YYYY → D/M/YYYY
* Hungarian: MM.DD.YYYY → YYYY. MM. DD.
* Icelandic: MM.DD.YYYY → D.M.YYYY
* Italian: MM.DD.YYYY → DD/MM/YYYY
* Japanese: MM.DD.YYYY → YYYY/MM/DD
* Language.new: MM.DD.YYYY → DD.MM.YYYY
* Luxembourgish: DD.MM.YYYY → D/M/YYYY
* Norwegian: MM.DD.YYYY → DD.MM.YYYY
* Polish: MM.DD.YYYY → D.MM.YYYY
* Portuguese: DD.MM.YYYY → DD/MM/YYYY
* Romanian: unchanged
* Russian: MM.DD.YYYY → DD.MM.YYYY
* Serbian: MM.DD.YYYY → D.M.YYYY
* Slovak: MM.DD.YYYY → D. M. YYYY
* Slovenian: MM.DD.YYYY → D. MM. YYYY
* Spanish: unchanged
* Swedish: MM.DD.YYYY → YYYY-MM-DD

### CODE REVIEW

**Comment by GrueneNeun** [comment]
Just wanted to say thanks for this change - I noticed that the format for English was not correct but never got around to open an issue...
I really appreciate it!

**Comment by lesderid** [comment]
I'm a native Dutch speaker, and `DD-MM-YYYY` is quite uncommon here. Officially it's `DD.MM.YYYY` or `YYYY-MM-DD`. In regular daily use I'd say the most common format is `DD/MM/YYYY`.

**Comment by barbeque-squared** [comment]
> I'm a native Dutch speaker, and `DD-MM-YYYY` is quite uncommon here (Flanders). Officially it's `DD.MM.YYYY` or `YYYY-MM-DD`. In regular daily use I'd say the most common format is `DD/MM/YYYY`.

`DD-MM-YYYY` is by far the most common one in the Netherlands (though unless a form forces me to, I prefer to use YYYY-MM-DD or `day fullwrittenmonth year`). Regardless, the PR is still an improvement over `MM.DD.YYYY`.

> unless specific versions of English can be added, such as UK and US English

I'm pretty sure this is possible, but I wouldn't bother until people start making issues about "I don't understand YYYY-MM-DD date format". Pretty sure they can also just make their own modified language file for this.

Anyway, thanks for this PR! I've changed the date format in my local builds ages ago, just never really got around to submit it. Mine would have only changed the English one, too, so this is a much more comprehensive PR. Expect it to get merged before the end of the week.

**Comment by PonPonTheBonBon** [comment]
@lesderid as stated in the commit, this is based on the latest data from CLDR v42

For Dutch (Dutch Netherlands) the format is `DD-MM-YYYY` while Dutch Belgium the format is `D/MM/YYYY`, so you are correct about Flanders. But I went with that Dutch in UltraStar was based on Netherlands. It would be possible to offer two Dutch translation if this change is important,

But CLDR does say it's `D/MM/YYYY` and not `DD/MM/YYYY`, meaning that the first day of this month would be 1/07/2023 and not 01/07/2023. This is how it should display in Windows, and on Apple and Android devices.

**Review by basisbit — APPROVED** [review]
Thank you so much for this improvement! I checked a bunch of them manually and asked friends from different countries to comment on the format choices, and they seem to fit well enough, at least much better than the previous default.

Kinda annoying that countries don't all just switch to the ISO standard for whatever reason 😅

**Pull request merged**
