### PR TITLE
Improve kerning across syllables

### PR DESCRIPTION
**Pull request by s09bQ5**
See #422

### CODE REVIEW

**Comment by bohning** [comment]
Travis build fails unfortunately, but it does not seem to be related to the changes of this PR.

After many warnings of the following type:
´ld: warning: object file (/usr/local/Cellar/fpc/3.0.4_1/lib/fpc/3.0.4/units/x86_64-darwin/rtl/cthreads.o) was built for newer OSX version (10.9) than being linked (10.5)´
the build fails with
´make[1]: *** No rule to make target `/usr/local/opt/jack/lib/libjack.0.dylib', needed by `UltraStarDeluxe.app/Contents/MacOS/libjack.0.dylib'.  Stop.
make: *** [macosx-standalone-app] Error 2´

@ePirat Can you help to fix this?

**Comment by ePirat** [comment]
I will check.

**Comment by ePirat** [comment]
This is weird… For some reason it assumes there should be a `libjack.0.dylib` which is not the case and fails.

**Comment by s09bQ5** [comment]
Apparently it broke again...  Homebrew/homebrew-core#24097
How about manually installing jack before building or using a newer version of ffmpeg?

**Comment by ePirat** [comment]
It should not even use jack I would argue as usage of jack on macOS is very rare… Though maybe they wanted to be complete and add as much dependencies as possible to their ffmpeg… *sigh*

Can we use a newer version of ffmpeg?

**Comment by basisbit** [comment]
*restarted travis builds

**Comment by bohning** [comment]
Can this PR be merged?

**Comment by bohning** [comment]
@s09bQ5 Unfortunately, when taking a closer look, it doesn't quite solve the issue, unfortunately. Looking at the screenshot below (upper line: no syllable division as reference, lower line: split into syllables), you can see that e.g. the spacing between ’mid’ and ’night’, between ’go’ and ’ing’ and between ’a’ and ’ny’ is somewhat too large, while it seems a little too small between ’ny’ and ’where’

bildschirmfoto 2019-01-08 um 02 12 11

**Comment by bohning** [comment]
As commented in #422, this pull request indeed solves all kerning issues. Thanks a lot!
Bildschirmfoto 2019-03-21 um 11 49 22

**Pull request merged**
