### PR TITLE
 CI/Windows: fix sourceforge download timeout

### PR DESCRIPTION
**Pull request by DeinAlptraum**
Un-silence newpascal download and extraction.
Use sourceforge's automatic mirror selection.

See #894

### CODE REVIEW

**Comment by s09bQ5** [comment]
Using netcologne already resulted in a redirect to the automatic mirror selection. It was the automatic mirror selection that had the SSL handshake timeout.

Can we make the powershell builtin output the progress?

**Comment by DeinAlptraum** [comment]
You mean like a progress bar for the download? 
I didn't see any such option [in the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.4)

**Comment by bohning** [comment]
> You mean like a progress bar for the download? I didn't see any such option [in the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.4)

Maybe this helps?
image

**Comment by basisbit** [comment]
If I remember correctly, it is common practice to not use the sourceforege mirror-selector, but instead pin it to a mirror which you prefer, because otherwise you rather often get random fails.

**Comment by s09bQ5** [comment]
But the netcologne mirror doesn't have the file we want and redirects us to the mirror selector:
https://github.com/UltraStar-Deluxe/USDX/actions/runs/10758015655/job/29832764850

**Comment by s09bQ5** [comment]
> `-ProgressAction Continue` should be the default, but let's try just in case.
> 
> Edit: didn't make a difference

According to https://www.youtube.com/watch?v=JwMJ35QEvSY the progress output of Invoke-WebRequest is temporarily drawn on top of previous output. I'd be surprised if this is done with escape sequences. It is probably directly manipulating the console contents, which doesn't work when the output is redirected to a logfile.

I think I prefer wget if Invoke-WebRequest is completely silent. Downloading with wget works even from downloads.sourceforge.net when raising the timeouts with `-T`. For the large newpascal download the progress output can be shortened to 10 lines with `--progress=dot:giga`.

**Comment by DeinAlptraum** [comment]
Changed this back to wget with increased timeout as well as changed progress bar like you suggested.

**Review by s09bQ5 — APPROVED** [review]

**Pull request merged**
