### PR TITLE
Remove old Visual Studio build rules

### PR DESCRIPTION
**Pull request by s09bQ5**
We don't use these files in our CI builds.
The DLL is shipped prebuilt in the game/ directory.

### CODE REVIEW

**Review by basisbit — APPROVED** [review]

**Comment by barbeque-squared** [comment]
Shouldn't the CI still try to build something for PR's? While this PR looks fine code wise, the CI has now gone completely silent, like it's not even attempting anything at all.

I expected it to show at least something referencing this PR on the History tab.

**Comment by s09bQ5** [comment]
@basisbit, did you disable AppVeyor in your Github settings when you heard that the build was broken?
It automatically built the remove-vcproj branch in https://github.com/s09bQ5/USDX.

**Comment by basisbit** [comment]
I have done nothing

**Comment by s09bQ5** [comment]
This PR is not the only one that didn't trigger a CI build. It's the same for #840 and #841.

**Pull request merged**
