### PR TITLE
Add MIDI support for other platform

### LINKED ISSUE #297: [Linux] Editor is unavailable
### Actual behaviour

When I go to Tools->Editor I get an error message "This feature is not available on this version"

### Expected behaviour

I'd like the editor to start

### Steps to reproduce

1. env LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/nvidia/current ultrastardx
2. Navigate to the editor
3. Try to start the editor

### Details

USDX version: 33fe22e3cfae1d67a74c0caa0ef4727027c597c3

Operating system: Debian testing (4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux)

### PR DESCRIPTION
**Pull request by s09bQ5**
This should fix #297.

So far only Linux has been tested. Windows still uses the old code, though it is also supported by PortMidi. I hope I didn't break support for Windows while restructuring the code. A fix for 64 bit architectures is also included. Btw., do we still support compilation with Delphi?

### CODE REVIEW

**Comment by s09bQ5** [comment]
Ok, I did break the windows build.
And on Linux Travis didn't build portmidi, so the new code wasn't built.

**Comment by abrock** [comment]
@s09bQ5 Thank you very much for working on this game.
I checked out your fork, uninstalled the game, made sure that the executable was gone, built and installed your version and started the game.
Unfortunately I still get the same error message when trying to enter the editor.

**Comment by s09bQ5** [comment]
@abrock 
And it did say "checking for Pm_Initialize in -lportmidi... yes" during configure?
And you do have an ALSA sequencer output device that is listed by "aconnect -l -o"?
And you did configure PortMidi with the PmDefaults Java application to create ~/.java/.userPrefs/PortMidi/prefs.xml?

**Comment by abrock** [comment]
> And it did say "checking for Pm_Initialize in -lportmidi... yes" during configure?

No. Then I installed libportmidi-dev and built usdx again and it did say that and I can enter the editor now 👍 

> And you do have an ALSA sequencer output device that is listed by "aconnect -l -o"?

No.

> And you did configure PortMidi with the PmDefaults Java application to create ~/.java/.userPrefs/PortMidi/prefs.xml?

No.

I can enter the editor, load a midi, select the voice and save it but UltrastarDX won't play it.

I made a minimal example:
[files.zip](https://github.com/UltraStar-Deluxe/USDX/files/1237059/files.zip)

lalalalaaa.ly: Lilypond file I used to create the midi.
lalalalaaa.midi: resulting midi
lalalalaaa.txt: File created by USDX editor. I added Title, Artist and MP3
lala.mp3: MP3 file I created from the midi using timidity and ffmpeg

I tried a txt file I downloaded from an USDX database and I could play it with USDX, everything worked as expected but when I remove it and only have my own mp3 and txt files in the songs directory the game says "now songs loaded".
I also looked at the txt files and I don't understand where my mistake is.
There is no corresponding error message in the console

**Comment by abrock** [comment]
I tried the same process with two more songs, both can't be read by USDX:

[antwort.zip](https://github.com/UltraStar-Deluxe/USDX/files/1237091/antwort.zip)
[raphael.zip](https://github.com/UltraStar-Deluxe/USDX/files/1237092/raphael.zip)

**Comment by abrock** [comment]
I figured it out:
I need to tell USDX where a line (or phrase) ends by inserting a line "- somenumber".
I'm not exactly sure how the syntax is and how I can get USDX to show me the next phrase when I want to see it. At the moment I want to always see the part I'm currently singing because I want to see if I make mistakes, but sometimes USDX switches to the next phrase too early.

**Comment by s09bQ5** [comment]
This is getting pretty off-topic. This discussion is supposed to be about my PortMidi patch.
If you want to hear USDX's MIDI output, start TiMidity++ with `timidity -iA -Os` and put 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="PM_RECOMMENDED_OUTPUT_DEVICE" value="TiMidity"/>
</map>
```
into ~/.java/.userPrefs/PortMidi/prefs.xml

**Comment by s09bQ5** [comment]
As I wrote on IRC, it still does not link to libportmidi.dylib on OS X, but it also does not fail linking. The symbols simply remain undefined. 3f9091b does not make any difference.
I can't debug this , so I'll just mention #167.

**Pull request merged**
