### PR TITLE
Add support for FFmpeg 5.0

### LINKED ISSUE #599: ffmpeg 5 support
### Actual behaviour

NixOS upgraded ffmpeg to 5.0 and the USDX configure script errored out.

```
checking for libavformat... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libavformat... [59.16.100]
checking for libavutil... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libavutil... [57.17.100]
checking for libswscale... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libswscale... [6.4.100]
checking for libswresample... yes (-L/nix/store/jaf390yiaqhwh15na2gw8cdnsngk7g7s-ffmpeg-5.0/lib)
checking version of libswresample... [4.3.100]
checking version of ffmpeg... configure: error:

Unsupported ffmpeg version, most recent version supported is 3.3.
```

It is interesting to note, that we previously used ffmpeg 4, so that error messages seems somewhat out of date.

### Expected behaviour

USDX should be updated to work with ffmpeg 5.0

### Steps to reproduce

Trivial.

### Details

Provide some additional information:

- USDX version: ade03ddd6d995a78c11de0ed3a1f052adc43ff12
- Operating System + version: NixOS 22.05 (unstable)

### PR DESCRIPTION
**Pull request by s09bQ5**
Many code changes. Barely tested.

Fixes #599

### CODE REVIEW

**Comment by bohning** [comment]
Wow, that was quick! I just tried to compile on macOS 12.1 Monterey, configure accepts ffmpeg5.0 without problems and the compilation seems to succeed. However, I run into a (I assume) unrelated problem:
image
and thus cannot execute the app.

**Comment by bohning** [comment]
Unfortunately, I just noticed that some videos are not displayed correctly. They are grayscale, tilted.

image

I remember that bug from way back years ago, not sure if it appeared with USDX CMD.

**Comment by s09bQ5** [comment]
Fixed. Libswscale with its undocumented requirements regarding width and stride...

**Comment by bohning** [comment]
> Fixed.

Awesome. Works like a charm now, thanks a lot!

**Review by bohning — APPROVED** [review]

**Pull request merged**
