### PR TITLE
Update Info.plist

### LINKED ISSUE #744: MacOS version number has never changed since 2020.4.0 - still at 1.3
the macOS download still contains 1.3

the CFBundleShortVersionString and CFBundleVersion key inside the info.plist should be updated:

```
[…]
	<key>CFBundleShortVersionString</key>
	<string>1.3</string>
	<key>CFBundleSignature</key>
	<string>USDX</string>
	<key>CFBundleVersion</key>
	<string>1.3</string>
[…]
```

Provide some additional information:

- Operating System + version: Ventura 13.4

### PR DESCRIPTION
**Pull request by bohning**
Closes #744.

### CODE REVIEW

**Review by barbeque-squared — APPROVED** [review]
> 1.3

That would explain why I never found this back when I was documenting what needs to be updated when doing a release. I'll want to have this documented in th erelevant .md, but it's also fine to do that in a separate ticket later on. There's no (automated) dev builds for Apple, so getting this file to show up at all when following the release instructions is already better than how things were.

Hereby approved.

**Comment by bohning** [comment]
I wasn't aware of it either. I can recompile and reupload 2023.9.0 in a few days.

**Comment by s09bQ5** [comment]
> I can recompile and reupload 2023.9.0 in a few days.

That should be 2023.9.1 then

**Comment by barbeque-squared** [comment]
Is this worth releasing an extra version over? It's been the wrong number for 7 years, is this an Apple thing that this cannot wait until the next regular release (which will probably be beginning of October)?
I do agree with s09bQ5 that the already uploaded 2023.9.0 should be left alone, since that tag won't have this fix yet. But since releases aren't actually merges, merging it as it is first would imo be the correct approach, that way it'll get incorporated in the _next_ release.

**Comment by basisbit** [comment]
@bohning sorry, won't be able to review this before beginning of next week. If someone else can handle this and test the build result on MacOS before then, that would be very nice.

**Review by basisbit — APPROVED** [review]

**Comment by basisbit** [comment]
yolo

**Pull request merged**
