### PR TITLE
Refactor singdraw

### PR DESCRIPTION
**Pull request by barbeque-squared**
There's more refactoring yet to come in this file/function, but its perfectly mergeable in the current state, plus it keeps these PRs from becoming way too complex to review.

For reviewing, I recommend going commit-per-commit instead of looking at the entire diff at once.

_Yes_ I'm aware it 'introduces' some constants at the top of the function. And some of them are deliberately still sums, because the numbers on the left side are also in other places, and for the right hand side there's _at least_ also a `105` that's related to that `95` somewhere.

### CODE REVIEW

**Comment by barbeque-squared** [comment]
Is there a reason the `help wanted` and `testers needed` labels were added to this? If the commits themselves don't give the confidence to merge this, testing this is just running this version and starting all the 1/2/3/4/6/duet/multiscreen combo's to verify that stuff is still in the same place.

It's also not particularly motivating because a few rounds of these kind of refactorings would _really_ help in cutting down the amount of changes when, for example, wanting to support more than six players (which I'm actually working on, but that's not ever going to get PR'd at this rate. And having to redo all my local fixes twice is really annoying).
I noticed that people like bohning or s09bQ5 are also fairly active, but none of us can actually do stuff.

**Comment by basisbit** [comment]
UltraStar Deluxe uses the typical github workflow:
1. someone created a pull request against main branch
2. at least one other person has to review and aprove the pr
3. checks all have to be green
4. then anyone with commit accesd to main can merge it.

Step 2 needs quite some time / effort to be done. I currently personally am busy. Others may help out as usual, thus the `help wanted` label.
For anything of a bigger change or anything compatibility related, soneone also has to test it. Thats what the `testers needed` label is for.

> but none of us can actually do stuff

Thats not true. See above. You can also fork your PR branch and keep working on other stuff, then later on do a PR for it again when the other stuff is done.

**Comment by HermannDppes** [comment]
I might not be qualified to review the code but I'd love to see this refactor come to the master in a reasonable time frame, too, so maybe I am at least qualified to hack together a bash script. Since most of this is just code reordering it seems reasonable to check that the code has no changes functionality semi-automatically. Going commit wise:

* [f3a8536](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/f3a8536c906ea3c1ce49bce8e11cbbadd3129cf3) I have not checked the correctness of these branch names. Well, I looked at a portion of them and they seemed reasonable but no guarantees (not the least because this would require code knowledge I do not have).
* [f3a8536](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/f3a8536c906ea3c1ce49bce8e11cbbadd3129cf3)..[6b1c2da](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/6b1c2da71f2558f0a8ec4dbafa0df61719f456f5) My little bash script concludes that – provided the branch name comments are correct – each of the branches stays the same. The lines have been regrouped, but ignoring white space and comments, each branch has the same lines in the same order as before.
* [6b1c2da](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/6b1c2da71f2558f0a8ec4dbafa0df61719f456f5)..[4e2998c](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/4e2998cb9aca293692096df75a95adb038873026) I have not checked whether the names of the variables make sense but the script says that where there now is a variable set to `0` there was a `0` before and where there is a variable set to `1` there was a `1` before.
* [4e2998c](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/4e2998cb9aca293692096df75a95adb038873026)..[22928cd](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/22928cdb61a71ce9c9f1d878421ed20e3066b1b3) The script informs me that in the case of `PlayersPlay = 1` the branch `SINGLESCREEN DUET` now has code it didn't used to have. This seems to be an artifact of there being no duet mode for a single player and hence the branches `SINGLESCREEN SOLO` and `SINGLESCREEN` being treated as interchangeable which the script does not understand. Otherwise, no changes (still assuming that all the branches are labelled correctly in the comments).
* [22928cd](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/22928cdb61a71ce9c9f1d878421ed20e3066b1b3)..[bd693cc](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/bd693cc9c65e7ab2ddafd23310a4132b26b06531) As with the previous introduction of variables, I do not know whether they make sense but my script says the numbers match.
* [bd693cc](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/bd693cc9c65e7ab2ddafd23310a4132b26b06531)..[1af83c0](https://github.com/UltraStar-Deluxe/USDX/pull/627/commits/1af83c06cfba3c7f66744275ba2ad86f43879537) As with both other variable changes I have no code knowledge but sed and diff are saying that no change in behaviour should occur.

The script did have a bunch of embarrassing bugs during development (and is therefore at risk of retaining some) but here it is in case anyone thinks their review process might be sped up by having it:
```bash
#!/bin/bash

UDraw='src/base/UDraw.pas'

SS='SINGLESCREEN SOLO';
M1S='MULTISCREEN 1 SOLO';
M2S='MULTISCREEN 2 SOLO';
SD='SINGLESCREEN DUET';
M1D='MULTISCREEN 1 DUET';
M2D='MULTISCREEN 2 DUET';

# Usage: extract PLAYER MODE FILE
#
# Extracts for the given number of players
# all the lines that happen in that mode
# (according to the comments from f3a8536)
# from the version of UDraw.pas found at the file path provided.
#
# These are interleaved with the corresponding sections
# according to the comments from d050f37 if present.
extract() {
	local PLAYER="$1"
	local MODE="$2"
	local FILE="$3"
	local PLAYER_SELECTOR='/^[0-9]*:  if PlayersPlay = '$PLAYER'/,/^[0-9]*:  end/'
	local MAIN_MODE_SELECTOR='/'"$MODE"'$/,/end/'
	local SUB_MODE="$(echo $MODE | sed 's/ SOLO\| DUET//')"
	local SUB_MODE_SELECTOR='/'"$SUB_MODE"'$/,/end/'
	cat \
		<(<$FILE grep -n . \
			| sed -n -e "$PLAYER_SELECTOR {$MAIN_MODE_SELECTOR p}" \
			| grep -v 'end' \
			| grep -v "$MODE") \
		<(<$FILE grep -n . \
			| sed -n -e "$PLAYER_SELECTOR {$SUB_MODE_SELECTOR p}" \
			| grep -v 'end' \
			| grep -v "$SUB_MODE") \
		| sort \
		| sed 's/^[0-9]*: *//'
}

check_trivial() {
	local OLD_REV=$1
	local NEW_REV=$2
	local TMP=$(mktemp -d)
	git show $OLD_REV:$UDraw >$TMP/old.pas
	git show $NEW_REV:$UDraw >$TMP/new.pas
	for PLAYERS in 1 2 3 4 6; do
		for MODE in "$SS" "$M1S" "$M2S" "$SD" "$M1D" "$M2D"; do
			diff \
				<(extract $PLAYERS "$MODE" $TMP/old.pas) \
				<(extract $PLAYERS "$MODE" $TMP/new.pas)
			if [[ $? -ne 0 ]]; then
    				echo "=== $OLD_REV vs. $NEW_REV ==="
				echo "=== Players: $PLAYERS, Mode: $MODE ==="
			fi
		done
	done
}

check_6b1c2da_4e2998c() {
	local OLD_REV='6b1c2da'
	local NEW_REV='4e2998c'
	local TMP=$(mktemp -d)
	git show $OLD_REV:$UDraw >$TMP/old.pas
	git show $NEW_REV:$UDraw >$TMP/new.pas
	for PLAYERS in 1 2 3 4 6; do
    		# Solos
		for MODE in "$SS" "$M1S" "$M2S"; do
			diff \
				<(extract $PLAYERS "$MODE" $TMP/old.pas) \
				<(extract $PLAYERS "$MODE" $TMP/new.pas \
					| sed 's/TrackP[1-6]/0/'
				)
			if [[ $? -ne 0 ]]; then
				echo "=== Players: $PLAYERS, Mode: $MODE ==="
			fi
		done
		# Duets
		for MODE in "$SD" "$M1D" "$M2D"; do
			diff \
				<(extract $PLAYERS "$MODE" $TMP/old.pas) \
				<(extract $PLAYERS "$MODE" $TMP/new.pas \
					| sed 's/TrackP[135]/0/' \
					| sed 's/TrackP[246]/1/'
				)
			if [[ $? -ne 0 ]]; then
    				echo "=== $OLD_REV vs. $NEW_REV ==="
				echo "=== Players: $PLAYERS, Mode: $MODE ==="
			fi
		done
	done
}

check_22928cd_bd693cc() {
	local OLD_REV='22928cd'
	local NEW_REV='bd693cc'
	local TMP=$(mktemp -d)
	git show $OLD_REV:$UDraw >$TMP/old.pas
	git show $NEW_REV:$UDraw >$TMP/new.pas
	for PLAYERS in 1 2 3 4 6; do
		for MODE in "$SS" "$M1S" "$M2S" "$SD" "$M1D" "$M2D"; do
			diff \
				<(extract $PLAYERS "$MODE" $TMP/old.pas) \
				<(extract $PLAYERS "$MODE" $TMP/new.pas \
					| sed 's/LineSpacingOneRow/15/' \
					| sed 's/LineSpacingTwoRows/15/' \
					| sed 's/LineSpacingThreeRows/12/'
				)
			if [[ $? -ne 0 ]]; then
    				echo "=== $OLD_REV vs. $NEW_REV ==="
				echo "=== Players: $PLAYERS, Mode: $MODE ==="
			fi
		done
	done
}

check_bd693cc_1af83c0() {
	local OLD_REV='bd693cc'
	local NEW_REV='1af83c0'
	local TMP=$(mktemp -d)
	git show $OLD_REV:$UDraw >$TMP/old.pas
	git show $NEW_REV:$UDraw >$TMP/new.pas
	for PLAYERS in 1 2 3 4 6; do
		for MODE in "$SS" "$M1S" "$M2S" "$SD" "$M1D" "$M2D"; do
			diff \
				<(extract $PLAYERS "$MODE" $TMP/old.pas) \
				<(extract $PLAYERS "$MODE" $TMP/new.pas \
					| sed 's/TopOneRow1/Skin_P2_NotesB/' \
					| sed 's/TopTwoRows1/Skin_P1_NotesB/' \
					| sed 's/TopTwoRows2/Skin_P2_NotesB/' \
					| sed 's/TopThreeRows1/120+95/' \
					| sed 's/TopThreeRows2/245+95/' \
					| sed 's/TopThreeRows3/370+95/'
				)
			if [[ $? -ne 0 ]]; then
    				echo "=== $OLD_REV vs. $NEW_REV ==="
				echo "=== Players: $PLAYERS, Mode: $MODE ==="
			fi
		done
	done
}

check_trivial f3a8536 6b1c2da
check_6b1c2da_4e2998c
check_trivial 4e2998c 22928cd
check_22928cd_bd693cc
check_bd693cc_1af83c0
```

**Comment by barbeque-squared** [comment]
@HermannDppes yeah the solo duet thing didn't really fit properly, but I was of the opinion that the increase in readability was a worthy tradeoff.

I also realized I accidentally broke your super nice commit number link thingies (I rebased my branch so that appveyor could build it), sorry about that.

I've been using the refactored version in my own builds for well over half a year now, I'm going to merge it soon because there's more refactoring to be done in this file.

**Pull request merged**
