### PR TITLE
add support for ffmpeg 4.2

### LINKED ISSUE #474: ffmpeg-4.2 support
### Actual behaviour

Building USDX against ffmpeg-4.2 on Archlinux with the AUR package (https://aur.archlinux.org/packages/ultrastardx-git) fails:

USDX/src/lib/ffmpeg-4.0/avutil.pas(81,4) Error: User defined: Linked version of libavutil is not yet supported!

### Expected behaviour

Successful build

### Steps to reproduce

Build USDX against the latest version of ffmpeg (currently ffmpeg-4.2 on Archlinux).

### Details

Provide some additional information:

- USDX version: git master branch, commit: 8d9b3e3
- Operating System + version: Arch Linux x86_64 Kernel 5.2.9-arch1-1-ARCH

### PR DESCRIPTION
**Pull request by luto**
fixed #474

Tested with one song and one player. Seems to work fine, but I don't have any experience using USDX myself.

### CODE REVIEW

**Comment by basisbit** [comment]
Did you check if there were any changes of the ffmpeg API that usdx uses?

**Comment by luto** [comment]
No, I did not. I'd love to, but I'm not familiar with usdx, ffmpeg or the ffmpeg APIs, sorry! Just wanted to leave this here in hope that it's useful to someone more experienced.

**Comment by basisbit** [comment]
ok, no problem. We'll check the ffmpeg documentation and then if everything looks fine, merge this pull request.

**Comment by bohning** [comment]
Any news on this? After updating ffmpeg from 4.1.4_2 to 4.2.1 via brew on my mac, I run into compliation problems (`avutil.pas(81,4) Error: User defined: Linked version of libavutil is not yet supported!`).

**Comment by bohning** [comment]
Works like a charm for me

**Pull request merged**
