### PR TITLE
USongs: Cache VisibleIndex

### LINKED ISSUE #320: Very low FPS (< 10) in Song selection
### Actual behaviour
When trying to select a song, a lot of them cause the FPS to drop below 10. It's very odd, since when I start the song the FPS go back to 60.

### Expected behaviour
Selecting a song shouldn't make FPS drop that much.

### Steps to reproduce

1. Open the Game
2. Select Players
3. Skimming through the song selection

### Details

Provide some additional information:

- USDX version: latest git as of 2017_11_09
- Operating System + version: 4.13.11-1-ARCH
- Graphics:

▶ lspci -nnk | grep -i VGA -A2 
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/580] [1002:67df] (rev c7)
	Subsystem: Micro-Star International Co., Ltd. [MSI] Radeon RX 480 [1462:3413]
	Kernel driver in use: amdgpu
~                                                                                                                                                                                            
▶ glxinfo | grep 'OpenGL version string' 
OpenGL version string: 3.0 Mesa 17.2.4

The same happens on Raspberry Pi as well as Core2Duo + Intel GMA 4500MHD in Ubuntu 17.04.4

### PR DESCRIPTION
**Pull request by s09bQ5**
It took a significant amount of time to calculate this value for huge collections.

Fixes #320

### CODE REVIEW

**Comment by cRaZy-bisCuiTs** [comment]
Thanks. I'll test tuesday nicht when I'm home!

**Comment by cRaZy-bisCuiT** [comment]
Well, it seems like the patch somehow works but is buggy:

- normal song selection using the arrow keys is MUCH improved, the performance is pretty good, even on a RaspberryPi 4 (default clock speed, fmks active)
- when pressing J to search for a song the song will play in the background but the GUI will crash and USDX freezes (segfault?)
- pressing R for random works as expected

**tail -f Error.log**
```
....
INFO:   Using decoder FFmpeg_Decoder for "/mnt/Images/7000_Ultrastar_Songs/10cc - Dreadlock Holiday [VIDEO]/10cc - Dreadlock Holiday.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   VideoStreamIndex : -1 [TVideoPlayback_ffmpeg.Open]
INFO:   Using h264_mmal codec [TVideoPlayback_ffmpeg.Open]
INFO:   Framerate: 6fps [TVideoPlayback_ffmpeg.Open]
INFO:   Using decoder FFmpeg_Decoder for "/mnt/Images/7000_Ultrastar_Songs/Astrid Lindgren - Du käre lille snickerbo/Astrid Lindgren - Du käre lille snickerbo.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/mnt/Images/7000_Ultrastar_Songs/Astrid Lindgren - Du käre lille snickerbo/Astrid Lindgren - Du käre lille snickerbo.mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   Using decoder FFmpeg_Decoder for "/mnt/Images/7000_Ultrastar_Songs/Lilly Wood & The Prick and Robin Schulz - Prayer in C (Robin Schulz Remix) [VIDEO]/Lilly Wood & The Prick and Robin Schulz - Prayer in C (Robin Schulz Remix).mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   VideoStreamIndex : -1 [TVideoPlayback_ffmpeg.Open]
INFO:   Using h264_mmal codec [TVideoPlayback_ffmpeg.Open]
INFO:   Framerate: 25fps [TVideoPlayback_ffmpeg.Open]
INFO:   Using decoder FFmpeg_Decoder for "/mnt/Images/7000_Ultrastar_Songs/Lilly Wood & The Prick and Robin Schulz - Prayer in C (Robin Schulz Remix) [VIDEO]/Lilly Wood & The Prick and Robin Schulz - Prayer in C (Robin Schulz Remix).mp3" [TAudioPlaybackBase.OpenDecodeStream]
INFO:   VideoStreamIndex : -1 [TVideoPlayback_ffmpeg.Open]
INFO:   Using h264_mmal codec [TVideoPlayback_ffmpeg.Open]
INFO:   Framerate: 25fps [TVideoPlayback_ffmpeg.Open]
```


**terminal output for USDX**
```
...
mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x3565300 (EINVAL)
mmal: mmal_port_disable: port vc.ril.video_decode:in:0(MP4V)(0x3565300) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x3565610) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x3577c90) is not enabled
mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x35a2470 (EINVAL)
mmal: mmal_port_disable: port vc.ril.video_decode:in:0(MP4V)(0x35a2470) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x3562f80) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x210fed0) is not enabled
mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x358aa50 (EINVAL)
mmal: mmal_port_disable: port vc.ril.video_decode:in:0(MP4V)(0x358aa50) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x358ad60) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x2115340) is not enabled
mmal: mmal_vc_port_info_set: failed to set port info (2:0): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x368aeb0 (EINVAL)
mmal: mmal_port_disable: port vc.ril.video_decode:in:0(MP4V)(0x368aeb0) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:out:0(0x368b1d0) is not enabled
mmal: mmal_port_disable: port vc.ril.video_decode:ctr:0(0x3679860) is not enabled

```

**Comment by cRaZy-bisCuiT** [comment]
**Update**
- random freezes also happen when just browsing using arrow keys to navigate (searching by pressing J causes reproducible freezes though)

PS: The music always keeps playing in the background

**Comment by s09bQ5** [comment]
Are we maybe opening a video before the previous one has been closed? Or are we leaking "something" used by MMAL?
It is rock solid with software decoding on my PC.

**Comment by cRaZy-bisCuiT** [comment]
I did not have this problem without this branch. I could try with SW decoding tonight.

**Comment by cRaZy-bisCuiT** [comment]
@s09bQ5 I guess you're on the right track:
- use software decoder: no crash. performance at RPI4 while decoding 1080p h.264 is abysmal again
- the error is still reproducible, also while searching for other songs and even if video preview is disabled

While the video preview is disabled, why does the application still render the video in the background? I can still see the decoder is in use. If we could not get this issue here fixed, disabling the video preview could at least be a mitigation if the video file would not be touched while skimming through the library or searching for a song.

It really seems the playback of a video is not terminated correctly and the hardware decoder might still be in use.

In addition, since I'm not able to get into the code base: Could this be related to our issue?
https://www.raspberrypi.org/forums/viewtopic.php?p=801310

**Comment by cRaZy-bisCuiT** [comment]
If someone else could test with a Pi3 or Pi4 that would be great. Maybe something might be wrong with my setup. I could try another clean flash of Raspian and re-compiling the game within this week.

**Comment by cRaZy-bisCuiT** [comment]
**Update**
Today I tried this PR again. I updated my Raspian to the latest version which brought a new ffmpeg version as well. Now I could use hardware encoding as well as the speeded up song selection.

I observed the performance got a little hit, the framerates at 1080p went down a little. I guess this is caused by the fact that RPI4 render pipeline/DRM is still a moving target. The drivers as well as the hardware codecs seem not to be optimized yet.

From my side I'd say the pr is totally fine to be merged. @s09bQ5 @basisbit

**Comment by basisbit** [comment]
could someone test this PR on usual windows and linux targets please?

**Comment by cRaZy-bisCuiT** [comment]
Works as well in Arch (with AMD RX480 Mesa Graphics) and Manjaro (with Intel UHD 620 Mesa).

I dont't have a bare metal Windows to test, though.

**Comment by cRaZy-bisCuiT** [comment]
PS: I'll test with +10.000 songs later tonight.

**Comment by basisbit** [comment]
also please test with categories enabled, with saved playlists and also with the different song browser modes to make sure that nothing broke that wasn't already broken before.

**Comment by s09bQ5** [comment]
I have rebased the commit.

**Comment by barbeque-squared** [comment]
Tested this on Arch with ~1900 songs, works fine as far as I'm able to tell. I played around with playlists, searches, searches within playlists, random, different sorting, different ways of song browsing (Roulette, Chessboard, etc) and did not notice any issues. I never use video previews (they slow down browsing).

Categories (assuming this is Options -> Game -> Tabs) have never worked for me. As in: I can select a category, and then I'm stuck in that category until I put the setting back to Off again; is this specific to certain theme/sorting/songbrowser/etc combination(s)?

**Comment by cRaZy-bisCuiTs** [comment]
The current version runs quite goog on Windows and Linux. Do we have a chance to merge it?

**Review by basisbit — APPROVED** [review]

**Comment by basisbit** [comment]
image
(just for the lulz)

**Pull request merged**
